const demo={customers:[{id:'C001',name:'Ananya Rao',email:'ananya@example.com'},{id:'C002',name:'Arjun Mehta',email:'arjun@example.com'},{id:'C003',name:'Diya Kumar',email:'diya@example.com'},{id:'C004',name:'Rohan Shah',email:'rohan@example.com'},{id:'C005',name:'Meera Iyer',email:'meera@example.com'}],products:[{id:'P001',name:'Smartphone X',cat:'Electronics',price:24999,stock:18,sold:24,icon:'◉'},{id:'P002',name:'Wireless Headphones',cat:'Electronics',price:3499,stock:7,sold:31,icon:'◌'},{id:'P003',name:'Everyday Hoodie',cat:'Clothing',price:1799,stock:22,sold:19,icon:'◇'},{id:'P004',name:'Running Shoes',cat:'Clothing',price:2999,stock:4,sold:27,icon:'△'},{id:'P005',name:'Organic Coffee',cat:'Grocery',price:599,stock:32,sold:16,icon:'○'},{id:'P006',name:'Snack Box',cat:'Grocery',price:449,stock:9,sold:12,icon:'□'}],orders:[{id:'ORD-1048',customer:'Ananya Rao',product:'Smartphone X',qty:1,total:23749,payment:'UPI',status:'Completed'},{id:'ORD-1047',customer:'Arjun Mehta',product:'Running Shoes',qty:2,total:5398,payment:'Card',status:'Completed'},{id:'ORD-1046',customer:'Diya Kumar',product:'Wireless Headphones',qty:1,total:3324,payment:'UPI',status:'Completed'},{id:'ORD-1045',customer:'Rohan Shah',product:'Organic Coffee',qty:3,total:1568,payment:'Cash',status:'Completed'},{id:'ORD-1044',customer:'Meera Iyer',product:'Everyday Hoodie',qty:2,total:3238,payment:'Card',status:'Completed'}]};
let data=JSON.parse(localStorage.getItem('cartiq-v2'))||structuredClone(demo),orderFilter='All';const $=s=>document.querySelector(s),money=n=>'₹'+Math.round(n||0).toLocaleString('en-IN');
function save(){localStorage.setItem('cartiq-v2',JSON.stringify(data));$('#syncTime').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});render()}
function revenue(){return data.orders.filter(o=>o.status==='Completed').reduce((a,o)=>a+o.total,0)}
function categoryTotals(){return ['Electronics','Clothing','Grocery'].map(cat=>({cat,total:data.orders.filter(o=>{const p=data.products.find(x=>x.name===o.product);return p?.cat===cat&&o.status==='Completed'}).reduce((a,o)=>a+o.total,0)}))}
function render(){const rev=revenue();$('#revenue').textContent=money(rev);$('#heroRevenue').textContent=money(rev);$('#orderCount').textContent=data.orders.length;$('#customerCount').textContent=data.customers.length;$('#lowStock').textContent=data.products.filter(p=>p.stock<10).length;renderChart();renderTop();renderOrders();renderProducts();renderCustomers();renderAnalytics()}
function renderChart(){const vals=categoryTotals(),max=Math.max(...vals.map(x=>x.total),1);$('#categoryChart').innerHTML=vals.map(x=>`<div class="bar-col"><span class="bar-value">${money(x.total)}</span><div class="bar-fill" style="--h:${Math.max(12,x.total/max*145)}px"></div><span class="bar-label">${x.cat}</span></div>`).join('')}
function renderTop(){const arr=[...data.products].sort((a,b)=>b.sold-a.sold).slice(0,5);$('#topProducts').innerHTML=arr.map((p,i)=>`<div class="top-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><div><b>${esc(p.name)}</b><small>${p.cat} · ${p.sold} units</small></div><strong>${money(p.price*p.sold)}</strong></div>`).join('')}
function renderOrders(){let arr=data.orders;if(orderFilter!=='All')arr=arr.filter(o=>o.status===orderFilter);const q=($('#globalSearch')?.value||'').toLowerCase();if(q)arr=arr.filter(o=>`${o.id} ${o.customer} ${o.product}`.toLowerCase().includes(q));$('#ordersTable').innerHTML=arr.length?arr.map(o=>`<tr><td><b>${esc(o.id)}</b></td><td>${esc(o.customer)}</td><td>${esc(o.product)}</td><td>${o.qty}</td><td>${o.payment||'—'}</td><td><b>${money(o.total)}</b></td><td><span class="status ${o.status==='Cancelled'?'cancelled':''}">${o.status}</span></td><td>${o.status!=='Cancelled'?`<button class="secondary" onclick="cancelOrder('${o.id}')">Cancel</button>`:''}</td></tr>`).join(''):'<tr><td colspan="8">No matching orders.</td></tr>'}
function renderProducts(search=''){const cat=$('#categoryFilter')?.value||'All',term=(search||$('#productSearch')?.value||'').toLowerCase();const arr=data.products.filter(p=>(cat==='All'||p.cat===cat)&&`${p.name} ${p.cat}`.toLowerCase().includes(term));$('#productGrid').innerHTML=arr.length?arr.map(p=>{const pct=Math.min(100,p.stock/40*100),low=p.stock<10;return `<div class="product-card"><div class="product-icon">${p.icon||'＋'}</div><h3>${esc(p.name)}</h3><span class="muted">${p.cat} · ${p.id}</span><div class="price">${money(p.price)}</div><div class="stock ${low?'low':''}"><i style="--stock:${pct}%"></i></div><div class="stock-row"><span>${p.stock} units available</span><b>${p.sold} sold</b></div></div>`}).join(''):'<div class="panel">No products match this filter.</div>'}
function renderCustomers(){const arr=data.customers.map(c=>({...c,total:data.orders.filter(o=>o.customer===c.name&&o.status==='Completed').reduce((a,o)=>a+o.total,0),orders:data.orders.filter(o=>o.customer===c.name).length}));$('#customerGrid').innerHTML=arr.map(c=>`<div class="customer-card"><div class="product-icon customer-icon">${initials(c.name)}</div><h3>${esc(c.name)}</h3><span class="muted">${esc(c.email)}</span><div class="price">${money(c.total)}</div><div class="stock-row"><span>${c.orders} order${c.orders===1?'':'s'}</span><b>Lifetime value</b></div></div>`).join('')}
function renderAnalytics(){const vals=categoryTotals(),max=Math.max(...vals.map(x=>x.total),1);$('#analyticsBars').innerHTML=vals.map(x=>`<div class="a-row"><b>${x.cat}</b><div class="track"><i style="--w:${x.total/max*100}%"></i></div><span>${money(x.total)}</span></div>`).join('');const low=[...data.products].sort((a,b)=>a.stock-b.stock)[0],top=[...data.products].sort((a,b)=>b.sold-a.sold)[0];$('#insights').innerHTML=`<div class="insight"><b>Top seller · ${esc(top?.name||'—')}</b><p>${top?.sold||0} units sold. This is the strongest product signal in the catalog.</p></div><div class="insight"><b>Inventory alert · ${esc(low?.name||'None')}</b><p>${low?`${low.stock} units remaining. Review replenishment before stock reaches zero.`:'All products are above the low-stock threshold.'}</p></div><div class="insight"><b>Revenue signal · ${money(revenue())}</b><p>${data.orders.filter(o=>o.status==='Completed').length} completed orders contribute to the current revenue KPI.</p></div>`;const spend=data.customers.map(c=>({name:c.name,total:data.orders.filter(o=>o.customer===c.name&&o.status==='Completed').reduce((a,o)=>a+o.total,0)})).sort((a,b)=>b.total-a.total);$('#customerRanking').innerHTML=spend.map((c,i)=>`<div class="customer-rank"><span class="num">${i+1}</span><div><b>${esc(c.name)}</b><small>Customer lifetime value</small></div><strong>${money(c.total)}</strong></div>`).join('')}
function showPage(id){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));const titles={dashboard:'Commerce control room',orders:'Orders',products:'Products',customers:'Customers',analytics:'Analytics',reports:'Reports'};history.replaceState(null,'','#'+id);document.title=`${titles[id]} | CartIQ`}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));const hash=location.hash.replace('#','');if(document.getElementById(hash))showPage(hash)}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function openCustomer(){modal(`<p class="eyebrow">CUSTOMER REGISTRATION</p><h2>Register customer</h2><div class="form"><label>FULL NAME</label><input id="cn" placeholder="e.g. Kavya Sharma"><label>EMAIL</label><input id="ce" type="email" placeholder="name@example.com"><button class="primary" onclick="addCustomer()">Create customer</button></div>`)}
function addCustomer(){const n=$('#cn').value.trim(),e=$('#ce').value.trim();if(n.length<2||!e.includes('@'))return toast('Enter a valid name and email');if(data.customers.some(c=>c.email.toLowerCase()===e.toLowerCase()))return toast('That email is already registered');data.customers.push({id:'C'+String(data.customers.length+1).padStart(3,'0'),name:n,email:e});save();closeModal();toast('Customer registered')}
function openProduct(){modal(`<p class="eyebrow">CATALOG MANAGEMENT</p><h2>Add product</h2><div class="form"><label>PRODUCT NAME</label><input id="pn" placeholder="e.g. Smart Watch"><label>CATEGORY</label><select id="pc"><option>Electronics</option><option>Clothing</option><option>Grocery</option></select><label>PRICE</label><input id="pp" type="number" min="1" placeholder="Price in ₹"><label>OPENING STOCK</label><input id="ps" type="number" min="0" placeholder="Units"><button class="primary" onclick="addProduct()">Add to catalog</button></div>`)}
function addProduct(){const n=$('#pn').value.trim(),p=Number($('#pp').value),s=Number($('#ps').value);if(!n||p<=0||s<0||!Number.isFinite(p)||!Number.isInteger(s))return toast('Enter valid product details');data.products.push({id:'P'+String(data.products.length+1).padStart(3,'0'),name:n,cat:$('#pc').value,price:p,stock:s,sold:0,icon:'＋'});save();closeModal();toast('Product added to catalog')}
function openOrder(){const available=data.products.filter(p=>p.stock>0);if(!data.customers.length||!available.length)return toast('Add a customer and an in-stock product first');modal(`<p class="eyebrow">ORDER DESK</p><h2>Place new order</h2><div class="form"><label>CUSTOMER</label><select id="oc">${data.customers.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select><label>PRODUCT</label><select id="op" onchange="updateOrderPreview()">${available.map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.price)} · ${p.stock} left</option>`).join('')}</select><label>QUANTITY</label><input id="oq" type="number" min="1" value="1" oninput="updateOrderPreview()"><label>PAYMENT</label><select id="pay"><option>UPI</option><option>Card</option><option>Cash</option></select><div id="orderPreview" class="order-total"><span>Estimated total</span><b>₹0</b></div><button class="primary" onclick="placeOrder()">Confirm order</button></div>`);updateOrderPreview()}
function updateOrderPreview(){const p=data.products.find(x=>x.id===$('#op')?.value),q=Number($('#oq')?.value||1);if(!p)return;const d=p.cat==='Electronics'?0.05:p.cat==='Clothing'?0.10:0.03;$('#orderPreview').innerHTML=`<span>${Math.round(d*100)}% category discount</span><b>${money(p.price*Math.max(0,q)*(1-d))}</b>`}
function placeOrder(){const p=data.products.find(x=>x.id===$('#op').value),q=Number($('#oq').value);if(!p||!Number.isInteger(q)||q<1||q>p.stock)return toast('Quantity exceeds available stock');const d=p.cat==='Electronics'?0.05:p.cat==='Clothing'?0.10:0.03,total=Math.round(p.price*q*(1-d));p.stock-=q;p.sold+=q;data.orders.unshift({id:'ORD-'+(1049+data.orders.length),customer:$('#oc').value,product:p.name,qty:q,total,payment:$('#pay').value,status:'Completed'});save();closeModal();toast('Order placed — inventory updated')}
function cancelOrder(id){const o=data.orders.find(x=>x.id===id);if(!o||o.status==='Cancelled')return;o.status='Cancelled';const p=data.products.find(x=>x.name===o.product);if(p){p.stock+=o.qty;p.sold=Math.max(0,p.sold-o.qty)}save();toast('Order cancelled — stock restored')}
function filterOrders(v,el){orderFilter=v;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderOrders()}
function globalSearch(v){const q=v.toLowerCase();document.querySelectorAll('.product-card,.customer-card').forEach(card=>{card.style.display=card.textContent.toLowerCase().includes(q)||!q?'':'none'});renderOrders()}
function resetDemo(){if(!confirm('Reset CartIQ to the original demo dataset?'))return;data=structuredClone(demo);save();toast('Demo dataset restored')}
function toggleTheme(){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'':'dark';localStorage.setItem('cartiq-theme',document.documentElement.dataset.theme)}
function csv(rows){const keys=Object.keys(rows[0]||{});return [keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCSV(kind){let rows=data[kind];if(kind==='customers')rows=data.customers.map(c=>({CustomerID:c.id,Name:c.name,Email:c.email,Orders:data.orders.filter(o=>o.customer===c.name).length,PurchaseValue:data.orders.filter(o=>o.customer===c.name&&o.status==='Completed').reduce((a,o)=>a+o.total,0)}));download(`cartiq-${kind}.csv`,csv(rows),'text/csv');toast(`${kind} CSV exported`)}
function exportReport(){const report={project:'CartIQ — E-Commerce Order and Customer Analytics System',generatedAt:new Date().toISOString(),kpis:{revenue:revenue(),orders:data.orders.length,customers:data.customers.length,lowStock:data.products.filter(p=>p.stock<10).length},customers:data.customers,products:data.products,orders:data.orders,categoryRevenue:categoryTotals()};download('cartiq-analytics-report.json',JSON.stringify(report,null,2),'application/json');toast('Analytics snapshot downloaded')}
function initials(n){return n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300)}
document.documentElement.dataset.theme=localStorage.getItem('cartiq-theme')||'';nav();render();